import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className='min-h-screen py-0 px-2 flex flex-col justify-center items-center h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='py-20 px-0 flex-1 flex-col justify-center items-center h-screen'>
        <h1 className='mx-0 my-0 leading-tight text-6xl text-center'>
          Image Effects!
          {/* Welcome to{' '}
          <a
            className='no-underline text-blue-600 hover:underline focus:underline active:underline'
            href='https://nextjs.org'
          >
            Next.js!
          </a> */}
        </h1>

        <p className='text-center leading-tight text-2xl'>
          Need to do some basic image manipulation? Just upload your image below
          and make the adjustments you'd like.
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>
      </main>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/master/examples'
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}

      <footer className='w-full h-24 border-t border-gray-300 flex justify-center items-center'>
        <a
          className='flex justify-center items-center flex-grow'
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className='h-4 flex-col'>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
